Repository vertelab/odoo-api, pull requests merged in 2020-12, with the labels that each got.

#5 [ADD] api_odoo_xmlrpc: AFC-1406 Updated code for api_odoo_xmlrpc modi…
  api_odoo_xmlrpc/__manifest__.py
  api_odoo_xmlrpc/models/odoo_api_synchro_obj.py
  api_odoo_xmlrpc/views/api_odoo_synchro_view.xml
  api_odoo_xmlrpc/wizard/api_odoo_synchro_view.xml
Labels: Prio 2

#8 [ADD] api_ipf AFC-1501: added module api_ipf
  api_ipf/__init__.py
  api_ipf/__manifest__.py
  api_ipf/models/__init__.py
  api_ipf/models/res_config_settings.py
  api_ipf/static/description/icon.png
  api_ipf/static/description/screen1.png
  api_ipf/views/res_config_settings_views.xml
Labels: Prio 1

#9 [ADD] api_odoo_xmlrpc: AFC-1406b Added button to test connection.
  api_odoo_xmlrpc/models/odoo_api_synchro_obj.py
  api_odoo_xmlrpc/views/api_odoo_synchro_view.xml
Labels: Prio 1, need install / smoke test

#10 [ADD] api_raindance_(client+server) AFC-1343: Add to DAFA sprint
  api_ipf_tlr_client/models/client_config.py
  api_ipf_tlr_client/views/client_config_views.xml
  api_raindance_client/__init__.py
  api_raindance_client/__manifest__.py
  api_raindance_client/models/__init__.py
  api_raindance_client/models/client_config.py
  api_raindance_client/models/request_history.py
  api_raindance_client/security/ir.model.access.csv
  api_raindance_client/static/description/icon.png
  api_raindance_client/views/client_config_views.xml
  api_raindance_server/__init__.py
  api_raindance_server/__manifest__.py
  api_raindance_server/controllers/__init__.py
  api_raindance_server/controllers/main.py
  api_raindance_server/controllers/token.py
  api_raindance_server/models/__init__.py
  api_raindance_server/models/ir_http.py
  api_raindance_server/static/description/icon.png
Labels: need install / smoke test
